### ISSUE TITLE
addDisclose

### ISSUE THREAD

**Issue by rstrzelecki** [AfriCC/php-epp2#1]
addDisclose seems to do nothing. Ideal should produce:

<?xml version="1.0" encoding="utf-8" standalone="no"?>
< epp xmlns="urn:ietf:params:xml:ns:epp-1.0" >
 < command >
 < update >
 < contact:update
 xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" >
 < contact:id >id8013< /contact:id >
 < contact:ch g>
 < contact:disclose flag="1" / >
 < /contact:chg >
 < /contact:update >
 < /update >
 < /command >
< /epp >

Space added to stop XML being stripped.

**Comment by lifeofguenter** [comment]
hey @rstrzelecki, sorry for not replying earlier I do not know why I did not receive any notification for this.

Anywho, I have seen you already fixed it in your fork. I will have a look at the problem and fix it here as well.

Thanks for reporting the bug! Highly appreciated!

**Comment by lifeofguenter** [comment]
There was a little more work to it, but I think I have got it right
