### ISSUE TITLE
How to set custom namespace to all commands/responses?

### ISSUE THREAD

**Issue by johnny-bit** [AfriCC/php-epp2#13]
Hi,

this maybe straightforward, but from single read through I can't figure it out yet - how to set custom namespace for all commands/reponses? 

something like:

``` php
public static $specs = [
        'epp'     => [
            'xmlns' => '/root/epp-3.0 epp.ns',
        ],
        'domain'  => [
            'xmlns' => '/root/epp/domain-3.0 domain.ns',
        ],
        'host'    => [
            'xmlns' => '/root/epp/host-3.0 host.ns',
        ],
        'contact' => [
            'xmlns' => '/root/epp/contact-3.0 contact.ns',
        ],
    ];
```

**Comment by lifeofguenter** [comment]
Hi,

do you have any documentation on what you are trying to do?

Thank you,
Gunter

**Comment by johnny-bit** [comment]
Oh, yeah. Sorry - I solved it like ~10mins after posting and simply forgot ;)

``` php
ObjectSpec::$specs = [
            'epp'     => [
            'xmlns' => '/root/epp-3.0 epp.ns',
        ],
        'domain'  => [
            'xmlns' => '/root/epp/domain-3.0 domain.ns',
        ],
        'host'    => [
            'xmlns' => '/root/epp/host-3.0 host.ns',
        ],
        'contact' => [
            'xmlns' => '/root/epp/contact-3.0 contact.ns',
        ],
    ];
```

BTW: wouldn't You mind some PRs in near future? I have extensions and another client implementation in my codebase, would be nice to share :) Just need to clear it up a bit & comment.

**Comment by lifeofguenter** [comment]
No problem. Sorry for my late response - did not get any notification. It would be interesting how you solved it though (also for others).

I am always very happy and thankful for PRs, So shoot :)

**Comment by johnny-bit** [comment]
So - to describe above code and solution: before initializing EPP client, I
set static `ObjectSpec::$specs` to what's above, and viola, Namespaces are
registered and all is working mighty fine :)

2015-09-08 15:30 GMT+02:00 Günter Grodotzki notifications@github.com:

> No problem. Sorry for my late response - did not get any notification. It
> would be interesting how you solved it though (also for others).
> 
> I am always very happy and thankful for PRs, So shoot :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AfriCC/php-epp2/issues/13#issuecomment-138559247.

## 

Pozdrawiam,
Hubert Kowalski

**Comment by lifeofguenter** [comment]
Thanks!
