### ISSUE TITLE
Client cerificate in epp call

### ISSUE THREAD

**Issue by webdotapp** [AfriCC/php-epp2#18]
Hello,

How can provide ssl client certificate in epp connection? I have searched everywhere but no solution. 

Please help.

**Comment by lifeofguenter** [comment]
You can do this here: https://github.com/AfriCC/php-epp2/blob/master/src/AfriCC/EPP/Client.php#L73

**Comment by webdotapp** [comment]
Thanks for your reply, but now i am getting following error...

```
Timeout while reading from EPP Server

Warning: unpack(): Type N: not enough input, need 4, have 0 in epp/vendor/africc/php-epp2/src/AfriCC/EPP/Client.php on line 177

```

**Comment by lifeofguenter** [comment]
This error handling indeed needs to be optimized. Can you do some debugging please or give me more details on what you are trying to do?

**Comment by naja7host** [comment]
i have tested , and is working fine for me .

**Comment by jkaflik** [comment]
@webdotapp Maybe your EPP server is using HTTP protocol? Isn't it?
I have done my own HTTP client implementation. I could consider do a PR. @lifeofguenter Would you like?

**Comment by jbarbede** [comment]
hey @lifeofguenter, I'm also having that error from time to time. I think the error posted by @webdotapp is the same that happened for me. It looks like when we try getting the greeting and read data from the socket, we get an empty result. I guess some network connection error could originate that.

The getFrame() method should probably check that the header received is not empty before unpacking it.

I really don't know how to reproduce it. I mean I'm pulling the whole day data from nic.mx EPP server but sometimes it just fails with that error.
