### ISSUE TITLE
services Extension

### ISSUE THREAD

**Issue by mCassy** [AfriCC/php-epp2#2]
How can I add options ?

```
<svcsExtension>
```

**Comment by lifeofguenter** [comment]
Hi,

can you give a more broader example? What are you trying to do? Which registrar?

Thank you.

**Comment by mCassy** [comment]
@lifeofguenter . Thank you for respond. I need to send request

```
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
    <command>
        <login>
            <clID>login</clID>
            <pw>pass</pw>
            <options>
                <version>1.0</version>
                <lang>en</lang>
            </options>
            <svcs>
                <objURI>http://hostmaster.ua/epp/host-1.1</objURI>
                <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
                <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
                <objURI>http://hostmaster.ua/epp/domain-1.1</objURI>
                <objURI>http://drs.ua/epp/drs-1.0</objURI>
                <objURI>http://hostmaster.ua/epp/contact-1.1</objURI>
                <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>
                <svcExtension>
                    <extURI>http://drs.ua/epp/drs-1.0</extURI>
                    <extURI>http://hostmaster.ua/epp/uaepp-1.1</extURI>
                </svcExtension>
            </svcs>
        </login>
        <clTRID>7917b0ee-15c0-4d14-9c10-bdf384e44bbe</clTRID>
    </command>
</epp>
```

**Comment by jbarbede** [comment]
+1

Registrar nicmx

``` xml
<svcs>
    <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
    <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>
    <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
    <svcExtension>
        <extURI>http://www.nic.mx/nicmx-msg-1.0</extURI>
        <extURI>http://www.nic.mx/nicmx-res-1.0</extURI>
    </svcExtension>
</svcs>
```

**Comment by lifeofguenter** [comment]
Please check - it includes a test and an example usage.

**Comment by mCassy** [comment]
@lifeofguenter Thanks a lot. I'm just trying to connect epp.uadns.com : 

```
<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

require 'src/AfriCC/autoload.php';

use AfriCC\EPP\Frame\Command\Login;
use AfriCC\EPP\Client as EPPClient;

if (!isset($_POST['host']))
die("Error");
$host = $_POST['host'];
$user = $_POST['user'];
$pass = $_POST['pass'];
$port = $_POST['port'];


$epp_client = new EPPClient([
    'host' => $host,
    'username' => $user,
    'password' => $pass,
    'services' => [
        'urn:ietf:params:xml:ns:epp-1.0',
    ],
    'debug' => true,
    'port' => $port,
 ]);
$greeting='';
try {
    $greeting = $epp_client->connect();
} catch(Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    unset($epp_client);
    exit(1);
}

$epp_client->close();
```

Result:

```
Timeout while reading from EPP Server [1;31m� domens-mnt-cunic-5538996700cc7 [0m[0;32m[0m[0;32m [0m
Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in ..\EPP\Frame\ResponseFactory.php on line 26
```

I can't find the error

**Comment by lifeofguenter** [comment]
Actually I forgot to implement the Client to also use the new feature.

Can you send me via email documentation and sandbox credentials so I can play around?

**Comment by jbarbede** [comment]
I created a fork with svcExtensions implemented into Client object and NICMX extension. Let me know if I should do a pull request.

I tested last commits, it works fine :-).

**Comment by lifeofguenter** [comment]
@jbarbede can you please create a pull request for:
- https://github.com/jbarbede/php-epp2/commit/07e0c428793d6ee1e7a8d00e4cbf3a110dd1bce1
- https://github.com/jbarbede/php-epp2/commit/72ec3f4ea04d00c1ba77a7c96a94b37d6606332e

This: https://github.com/jbarbede/php-epp2/commit/91628669b57d212fd803467d63c488961fed66db - is pretty good and should be added, but it would also have to be implemented on domain-updates, I suppose?

This: https://github.com/jbarbede/php-epp2/commit/36629cd33110b07c14b848d064689e7acb6802f6 cannot be automatically merged yet as of yet, I will have to dig into the MX documentation and see what output is being expected and might apply the changes you suggest. In general though I'd be very interested in pulling in additional extensions.

**Comment by jbarbede** [comment]
@lifeofguenter, I sent you 2 pull requests: svcExtensions + typo fix for the Client, billing contact for domain creation/update.

For NICMX and this change into AbstractFrame, no problem check MX doc and let me know how do you like to implement these specific functions offered by NICMX.

**Comment by lifeofguenter** [comment]
Thanks @jbarbede highly appreciated. You might want to maybe add your correct email in your github account/commit config - so your github username will show up under contributors.

I will close here now.

@mCassy: if you still have further problems, please email me: gunter@grodotzki.co.za with documentation and sandbox credentials.
