### ISSUE TITLE
sendFrame $header question 

### ISSUE THREAD

**Issue by karborator** [AfriCC/php-epp2#26]
Hello , 
what is the purpose of creating a $header and after that appending it to the buffer before sending the request . Client.php 

  $header = pack('N', mb_strlen($buffer, 'ASCII') + 4);
  return $this->send($header . $buffer);

**Comment by lifeofguenter** [comment]
- we are not appending the header, but prepending it
- it is part of the EPP protocol to prepend the length of every body that is being sent/written
- if you see any way of improving it (or if I am doing it wrong in first place) - please advise :)
