### ISSUE TITLE
Change host ( name server ) 

### ISSUE THREAD

**Issue by karborator** [AfriCC/php-epp2#27]
How can i update  name server ? 

$frame = new UpdateHost;
$frame->setHost('ns1.example.com');
$frame->changeHost('ns1.anotherexample.com');

response - "Unimplemented option"

**Comment by lifeofguenter** [comment]
Hi @karborator, the `Host` - Update is fully implemented as described here: https://tools.ietf.org/html/rfc5732#section-3.2.5 (at least I hope so), and you can find that as an example usage here: https://github.com/AfriCC/php-epp2/blob/master/examples/update_host.php

I suppose not every domain registrar/registry will implement the full EPP protocol stack, so in worse case you might have to delete the host and recreate it?

Please note, this feature is not necessarily needed to register domains with a namserver-set, but is commonly known as setting "glue records".
