### ISSUE TITLE
Configurable buffer chunk size

### ISSUE THREAD

**Issue by nidzho** [AfriCC/php-epp2#28]
Hello,
some EPP server(s) don't like the buffer chunk size (they disconnect immediately after 2nd loop iteration).
https://github.com/AfriCC/php-epp2/blob/master/src/AfriCC/EPP/Client.php#L343-L345
#29

**Comment by nidzho** [comment]
#29

**Comment by lifeofguenter** [comment]
Awesome! Your PR is merged. May I ask what EPP server was causing troubles?

**Comment by nidzho** [comment]
Serbian registry RNIDS for .RS domains, they switched to EPP last week.

EPP server was closing TCP connection so I was getting "Got a bad frame header length of 0 bytes from peer" errors (but obviously only for commands which ended up larger than 1 KB, it was kinda tricky to diagnose at first).

Thank you for the great PHP based EPP client!
