### ISSUE TITLE
add new command to library 

### ISSUE THREAD

**Issue by naja7host** [AfriCC/php-epp2#30]
Hello , i want to add a restore command to the library , but i have a dificult to add it , how i can add this command to the epp class ? 
 `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
  <epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0
   epp-1.0.xsd">
  <command>
   <update>
        <domain:update
        xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
         xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0
         domain-1.0.xsd">
          <domain:name>example.com</domain:name>
          <domain:chg/>
        </domain:update>
      </update>
      <extension>
        <rgp:update xmlns:rgp="urn:ietf:params:xml:ns:rgp-1.0"
         xsi:schemaLocation="urn:ietf:params:xml:ns:rgp-1.0
         rgp-1.0.xsd">
          <rgp:restore op="request"/>
        </rgp:update>
      </extension>
      <clTRID>ABC-12345</clTRID>
    </command>
  </epp>
`

**Comment by lifeofguenter** [comment]
Can you please provide a link to the documentation? This looks like a common feature but the implementation might be bound to only a few registrars.

**Comment by naja7host** [comment]
look here https://tools.ietf.org/html/rfc3915#page-13

i have added a new extention called RESTORE with a new file rgp.php , then i have implemented the function in my test app , it work well . 

so create a file in AfriCC\EPP\Extension\RESTORE\Update\Rgp.php

the content is here https://gist.github.com/naja7host/b6009d80c35fc8c6175178d309363e08
to use it : 

Request Restore 

```
                $frame = new  AfriCC\EPP\Extension\RESTORE\Update\Rgp;
                $frame->setDomain('domain');
                $frame->restoreDomainRequest();
```

to request restore with report 

```
                $frame = new  AfriCC\EPP\Extension\RESTORE\Update\Rgp;
                $frame->setDomain('domain');
                $frame->restoreDomain();
                $frame->setpreData('registrant_id');
                $frame->setpostData('registrant_id');
                $frame->setdelTime(date('c'));
                $frame->setresTime(date('c'));
                $frame->setresReason("CHANGED_MIND");
                $frame->setstatement("Restore Statement line 1");
                $frame->setstatement("Restore Statement line 2"); //optional
                $frame->setsetother("se tother statement"); //optional

```

if you found it usefull you can add it to the project .

**Comment by lifeofguenter** [comment]
Awesome, thanks so much @naja7host ! It seems like this is all described (as you linked) under: rfc3915 - so I would like to support that as a whole.

I'd most prolly not use the `Extension` namespace, as that is reserved for the quirks of the different registries, however I'd maybe introduce a new namespace `Mappings` that would add additional functionality on-top of the core EPP commands.

So something like `Mappings\GracePeriod\Create\xxx`

**Comment by naja7host** [comment]
So go with it ...

**Comment by naja7host** [comment]
Any update in this ?

**Comment by lifeofguenter** [comment]
Sorry for the late reaction. Implemented here: https://github.com/AfriCC/php-epp2/pull/45 - thanks a lot for the initial work. Please let me know if this is working for you. I used https://tools.ietf.org/html/rfc3915 as template for the tests.
