### ISSUE TITLE
Missing transfer operation type: query

### ISSUE THREAD

**Issue by jbarbede** [AfriCC/php-epp2#5]
According to http://tools.ietf.org/html/rfc5730#page-52, you have also "query" for transfer operation types.

**Comment by lifeofguenter** [comment]
You mean this: http://tools.ietf.org/html/rfc5730#section-2.9.2.4 ?

**Comment by jbarbede** [comment]
Yes, exactly.

**Comment by lifeofguenter** [comment]
added example file - obviously you need to check out and do stuff with the response with your application itself :)
