### ISSUE TITLE
Support for nic.it

### ISSUE THREAD

**Issue by bessone** [AfriCC/php-epp2#78]
**Nic.it** is the Registry of **.it** Internet domains, it uses some extensions for custom operations, the guidelines are available in this pdf file:
https://www.nic.it/sites/default/files/documenti/2019/Synchronous_Technical_Guidelines_v2.5.pdf

The extension of some commands allows to manage the Italian domains and contacts.

PR shortly. #

**Comment by lifeofguenter** [comment]
thanks for your contribution 🙇
