### ISSUE TITLE
Travis CI fail on PHP 5.5

### ISSUE THREAD

**Issue by bessone** [AfriCC/php-epp2#80]
Travis CI is failing the PHP 5.5 test because it cannot be run on Ubuntu Xenial.
More info here:
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

The solution is to remove PHP 5.5 (EOL 2016-07-21) or change travis.yaml to force the use of Ubuntu Trusty

**Comment by lifeofguenter** [comment]
nice one @bessone , thanks for the fix! I can not remove PHP5.5 just yet because google-app-engine still supports it.
