### ISSUE TITLE
Composer Release still in 1.0.0

### ISSUE THREAD

**Issue by naja7host** [AfriCC/php-epp2#90]
when we use composer to download the package, the version downloaded is 1.0.0 wish it lock some updates from the latest months, please update the release to include the last commit.

**Comment by naja7host** [comment]
any update in this ?

**Comment by krtcom** [comment]
Hi there, any plans for releasing new version? Mostly looking forward to DNSSec support so we don't have to roll our own solution since we are already using this library. Thanks for all the good work :-)

**Comment by krtcom** [comment]
BTW if time is all that is needed I am willing to help, maintainer maybe?

**Comment by johnny-bit** [comment]
I'd love to co maintain!

pt., 23 paź 2020, 07:42 użytkownik krtcom <notifications@github.com>
napisał:

**Comment by bessone** [comment]
Hello,
the project 
have commits from a few months ago, but the latest release is very old. do maintainers want to create a new release?

**Comment by naja7host** [comment]
up

**Comment by lifeofguenter** [comment]
New release available :)
